# Generated by Django 2.2.3 on 2019-07-23 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mytutor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='asked_by',
        ),
        migrations.RemoveField(
            model_name='question',
            name='subject',
        ),
    ]
